# Specify input
from_data:
  data_stem: "../data/challenging_toy_fewer_tasks/toy"
  phase_ids:
    - 0
check_schema: true

# Specify work model
work_model:
  name: AffineCombination
  parameters:
    alpha: 1.
    beta: 0.
    gamma: 0.
    upper_bounds:
      max_memory_usage: 8.0e+9

# Specify balancing algorithm
algorithm:
  name: InformAndTransfer
  phase_id: 0
  parameters:
    n_iterations: 8
    n_rounds: 4
    fanout: 4
    order_strategy: arbitrary
    transfer_strategy: Clustering
    criterion: Tempered
    max_objects_per_transfer: 100
    deterministic_transfer: True

# Specify output
output_dir: ../output
output_file_stem: output_file
LBAF_Viz:
  x_ranks: 4
  y_ranks: 4
  z_ranks: 1
  object_jitter: 0.5
  #rank_qoi: homed_blocks_ratio
  rank_qoi: max_memory_usage
  object_qoi: shared_block_id
  save_meshes: False
