# Specify input
from_data:
  data_stem: ../data/challenging_toy_hundreds_tasks/toy
  phase_ids:
    - 0
check_schema: true
overwrite_validator: false

# Specify work model
work_model:
  name: AffineCombination
  parameters:
    alpha: 1.0
    beta: 0.0
    gamma: 0.0
    upper_bounds:
      max_memory_usage: 8000000000.0

# Specify algorithm
algorithm:
  name: InformAndTransfer
  phase_id: 0
  parameters:
    n_iterations: 8
    n_rounds: 4
    fanout: 4
    order_strategy: arbitrary
    transfer_strategy: Clustering
    criterion: Tempered
    max_objects_per_transfer: 500
    deterministic_transfer: False

# Specify output
output_dir: ../output
output_file_stem: output_file
LBAF_Viz:
  x_ranks: 8
  y_ranks: 8
  z_ranks: 1
  object_jitter: 0.5
  rank_qoi: load
  save_meshes: False
  force_continuous_object_qoi: True
