algorithm:
  name: InformAndTransfer
  parameters:
    criterion: Tempered
    deterministic_transfer: false
    fanout: 4
    max_objects_per_transfer: 500
    n_iterations: 8
    n_rounds: 4
    order_strategy: arbitrary
    transfer_strategy: Clustering
  phase_id: 0
check_schema: true
from_data:
  data_stem: ../data/challenging_toy_hundreds_tasks/toy
  phase_ids:
  - 0
output_dir: ../output
output_file_stem: output_file
overwrite_validator: false
visualization:
  force_continuous_object_qoi: true
  object_jitter: 0.5
  output_visualization_dir: ../output
  output_visualization_file_stem: output_file
  rank_qoi: load
  save_meshes: false
  x_ranks: 8
  y_ranks: 8
  z_ranks: 1
work_model:
  name: AffineCombination
  parameters:
    alpha: 1.0
    beta: 0.0
    gamma: 0.0
    upper_bounds:
      max_memory_usage: 8000000000.0
