# Specify input
from_data:
  data_stem: ../data/challenging_toy_fewer_tasks/toy
  phase_ids:
  - 0
check_schema: true
overwrite_validator: false

# Specify work model
work_model:
  name: AffineCombination
  parameters:
    beta: 0.0
    gamma: 0.0
    upper_bounds:
      max_memory_usage: 8.0e+9

# Specify balancing algorithm
algorithm:
  name: InformAndTransfer
  phase_id: 0
  parameters:
    n_iterations: 8
    n_rounds: 4
    fanout: 4
    order_strategy: arbitrary
    transfer_strategy: Clustering
    criterion: Tempered
    max_objects_per_transfer: 100
    deterministic_transfer: true

# Specify output
output_dir: ../output
output_file_stem: output_file
