# Specify input
from_data:
  data_stem: ../data/challenging_toy_hundreds_tasks/toy
  phase_ids:
  - 0
check_schema: true
overwrite_validator: false

# Specify work model
work_model:
  name: AffineCombination
  parameters:
    beta: 0.0
    gamma: 0.0
    delta: 0.0
    upper_bounds:
      max_memory_usage: 8000000000.0

# Specify algorithm
algorithm:
  name: InformAndTransfer
  phase_id: 0
  parameters:
    n_iterations: 4
    n_rounds: 3
    fanout: 4
    order_strategy: arbitrary
    transfer_strategy: Clustering
    max_subclusters: 0
    cluster_swap_rtol: 0.05
    criterion: Tempered
    max_objects_per_transfer: 500
    deterministic_transfer: false

# Specify output
output_dir: ../output
output_file_stem: output_file
