algorithm:
  name: InformAndTransfer
  parameters:
    criterion: Tempered
    deterministic_transfer: true
    fanout: 2
    max_objects_per_transfer: 8
    n_iterations: 8
    n_rounds: 2
    order_strategy: arbitrary
    transfer_strategy: Recursive
  phase_id: 0
check_schema: false
from_data:
  data_stem: ../data/synthetic_lb_data/data
  phase_ids:
  - 0
output_dir: ../output
output_file_stem: output_file
visualization:
  force_continuous_object_qoi: true
  object_jitter: 0.5
  object_qoi: load
  output_visualization_dir: ../output
  output_visualization_file_stem: output_file
  rank_qoi: work
  save_meshes: true
  x_ranks: 2
  y_ranks: 2
  z_ranks: 1
work_model:
  name: AffineCombination
  parameters:
    alpha: 0.0
    beta: 1.0
    gamma: 0.0
write_JSON:
  communications: true
  compressed: false
  offline_LB_compatible: false
  suffix: json
