# Docs
# parameter_name [type]        description
# ---------------------------  -----------------------------------------------------------------------
# from_data:
#   data_stem [str]            base file name of VT load logs
#   phase_ids [list or str]    list of ids of phase to be read in VT load logs e.g. [1, 2, 3] or "1-3"
# from_samplers [dict]
#   n_objects [int]            number of objects
#   n_mapped_ranks [int]       number of initially mapped processors
#   communication_degree [int] object communication degree (no communication if 0)
#   load_sampler               description of object load sampler:
#     name [str]               in uniform, lognormal
#     parameters [list]        parameters e.g. 1.0,10.0 for lognormal
#   volume_sampler             description of object communication volumes sampler:
#     name [str]               in uniform, lognormal
#     parameters [list]        parameters e.g. 1.0,10.0 for lognormal
# check_schema  [bool]         validates that configuration is valid with the configuration schema
# work_model [dict]            work model to be used
#   name [str]                 in LoadOnly, AffineCombination
#   parameters [dict]          optional parameters specific to each work model
# algorithm [dict]             balancing algorithm to be used
#   name [str]                 in InformAndTransfer, BruteForce, PhaseStepper
#   parameters [dict]          parameters specific to each algorithm:
#     InformAndtransfer [dict] InformAndtransfer algorithm parameters
#       criterion [str]        in Tempered (default), StrictLocalizer
#       n_iterations [int]     number of load-balancing iterations
#       deterministic_transfer [bool] for deterministic transfer (default: False)
#       n_rounds [int]         number of information rounds
#       fanout [int]           information fanout index
#       order_strategy [str]   ordering of objects for transfer
#                              in arbitrary (default), element_id, increasing_times
#                              decreasing_times, increasing_connectivity,
#                              fewest_migrations, small_objects
#      BruteForce [dict]       BruteForce algorithm parameters
#        skip_transfer [bool]  skip transfer phase (default: False)
#      PhaseStepper [dict]     PhaseStepper algorithm parameters
# logging_level [str]          set to `info`, `debug`, `warning` or `error`
# log_to_file [str]            filepath to save the log file (optional)
# output_dir [str]             output directory (default: '.')
# LBAF_Viz [dict]              Visualization parameters (optional)
#   x_ranks [int]              number of ranks in x direction for rank visualization
#   y_ranks [int]              number of ranks in y direction for rank visualization
#   z_ranks [int]              number of ranks in z direction for rank visualization
#   object_jitter [float]      coefficient of random jitter with magnitude < 1
#   rank_qoi [str]             in load, work, None
#   object_qoi [str]           in load, work, None
#   save_meshes [bool]         generate mesh outputs (default: False)
#   force_continuous_object_qoi [bool] always treat object QOI as continuous or not
# file_suffix [str]            file suffix of VT data files (default: "json")
# communication_degree [int]   object communication degree (no communication if 0)
# write_JSON                   write load directives for VT as JSON files
#   compressed [bool]          compress json files using brotli
#   suffix [str]               suffix for generates files. (default: "json")
#   communications [bool]      use communications (default: False)
#   offline_LB_compatible [bool] (default: False)

# Specify input
from_data:
  data_stem: ../data/synthetic_lb_data/data
  phase_ids:
    - 0
check_schema: False

# Specify work model
work_model:
  name: AffineCombination
  parameters:
    alpha: 0.0
    beta: 1.0
    gamma: 0.0

# Specify algorithm
algorithm:
  name: InformAndTransfer
  phase_id: 0
  parameters:
    n_iterations: 8
    n_rounds: 4
    fanout: 4
    order_strategy: arbitrary
    transfer_strategy: Recursive
    criterion: Tempered
    max_objects_per_transfer: 8
    deterministic_transfer: True

# Specify output
output_dir: ../output
output_file_stem: output_file
LBAF_Viz:
  x_ranks: 2
  y_ranks: 2
  z_ranks: 1
  object_jitter: 0.5
  rank_qoi: work
  object_qoi: load
  save_meshes: True
  force_continuous_object_qoi: True
write_JSON:
  compressed: False
  suffix: json
  communications: True
  offline_LB_compatible: False
