# Specify input
from_data:
  data_stem: ../data/synthetic_lb_data/data
  phase_ids:
    - 0

# Specify work model
work_model:
  name: AffineCombination
  parameters:
    alpha: 0.0
    beta: 1.0
    gamma: 0.0

# Specify algorithm
algorithm:
  name: InformAndTransfer
  parameters:
    n_iterations: 8
    n_rounds: 4
    fanout: 4
    order_strategy: arbitrary
    transfer_strategy: Recursive
    criterion: Tempered
    max_objects_per_transfer: 8
    deterministic_transfer: true

# Specify output
check_schema: false
output_dir: ../output
output_file_stem: output_file
n_ranks: 4
LBAF_Viz:
  x_ranks: 2
  y_ranks: 2
  z_ranks: 1
  object_jitter: 0.5
  rank_qoi: work
  object_qoi: load
  save_meshes: true
  force_continuous_object_qoi: true
