# Docs
# parameter_name [type]        description
# ---------------------------  -----------------------------------------------------------------------
# work_model                   work model to be used
#   name [str]                 in LoadOnly, AffineCombination
#   parameters: [dict]         optional parameters specific to each work model
# algorithm                    balancing algorithm to be used
#   name [str]                 in InformAndTransfer, BruteForce, PhaseStepper
#   parameters: [dict]         parameters specitic to each algorithm:
#     InformAndtransfer:       InformAndtransfer algorithm parameters
#       criterion [str]        in Tempered (default), StrictLocalizer
#       n_iterations [int]     number of load-balancing iterations
#       deterministic_transfer [bool] for deterministic transfer (default: False)
#       n_rounds [int]         number of information rounds
#       fanout [int]           information fanout index
#       order_strategy [str]   ordering of objects for transfer
#                              in arbitrary (default), element_id, increasing_times
#                              decreasing_times, increasing_connectivity,
#                              fewest_migrations, small_objects
#      BruteForce:             BruteForce algorithm parameters
#        skip_transfer [bool]  skip transfer phase (default: False)
#      PhaseStepper            PhaseStepper algorithm parameters
# logging_level [str]          set to `info`, `debug`, `warning` or `error`
# log_to_file [str]            filepath to save the log file (optional)
# x_procs [int]                number of procs in x direction for rank visualization
# y_procs [int]                number of procs in y direction for rank visualization
# z_procs [int]                number of procs in z direction for rank visualization
# data_stem [str]              base file name of VT load logs
# phase_ids [list or str]      list of ids of phase to be read in VT load logs e.g. [1, 2, 3] or "1-3"
# map_file [str]               base file name for VT object/proc mapping
# file_suffix [str]            file suffix of VT data files (default: "json")
# output_dir [str]             output directory (default: '.')
# terminal_background [str]    background color for terminal output
# generate_meshes [bool]       generate mesh outputs (default: False)
# generate_multimedia [bool]   generate multimedia visualization (default: False)
# n_objects [int]              number of objects
# n_mapped_ranks [int]         number of initially mapped processors
# communication_degree [int]   object communication degree (no communication if 0)
# time_sampler                 description of object times sampler:
#    name [str]                in uniform, lognormal
#    parameters [list]         parameters e.g. 1.0,10.0 for lognormal
# volume_sampler               description of object communication volumes sampler:
#    name [str]                in uniform, lognormal
#    parameters [list]         parameters e.g. 1.0,10.0 for lognormal
# write_JSON:                  write load directives for VT as JSON files
#   compressed: [bool]         compress json files using brotli
#   suffix: [str]              suffix for generates files. (default: "json")
#   communications: [bool]     use communications (default: False)
#   offline_LB_compatible: [bool] (default: False)

# Specify input
from_data:
  data_stem: ../data/synthetic_lb_data/data
  phase_ids:
    - 0
check_schema: False

# Specify work model
work_model:
  name: AffineCombination
  parameters:
    alpha: 0.0
    beta: 1.0
    gamma: 0.0

# Specify algorithm
algorithm:
  name: InformAndTransfer
  phase_id: 0
  parameters:
    n_iterations: 8
    n_rounds: 4
    fanout: 4
    order_strategy: arbitrary
    transfer_strategy: Recursive
    criterion: Tempered
    max_objects_per_transfer: 8
    deterministic_transfer: True

# Specify output
output_dir: ../output
output_file_stem: output_file
n_ranks: 4
LBAF_Viz:
  x_ranks: 2
  y_ranks: 2
  z_ranks: 1
  object_jitter: 0.5
  rank_qoi: work
  object_qoi: load
  save_meshes: True
  force_continuous_object_qoi: True
write_JSON:
  compressed: False
  suffix: json
  communications: True
  offline_LB_compatible: False
