# Specify input
from_data:
  data_stem: ../data/nolb-8color-16nodes-every50phases/stats
  phase_ids:
    - 2
    - 52
    - 102
    - 152
    - 202
    - 252
    - 302
    - 352
    - 402
    - 452
    - 502
    - 552
    - 602
    - 652
    - 702
    - 752
    - 802
    - 852
    - 902
    - 952

# Specify work model
work_model:
  name: AffineCombination
  parameters:
    alpha: 1.0
    beta: 1.0e-08
    gamma: 0.0

# Specify algorithm
algorithm:
  name: PhaseStepper

# Specify output
output_dir: ../output
output_file_stem: output_file
LBAF_Viz:
  x_ranks: 8
  y_ranks: 4
  z_ranks: 1
  object_jitter: 0.5
  rank_qoi: work
  force_continuous_object_qoi: True
