algorithm:
  name: PhaseStepper
from_data:
  data_stem: ../data/nolb-8color-16nodes-every50phases/stats
  phase_ids:
  - 2
  - 52
  - 102
  - 152
  - 202
  - 252
  - 302
  - 352
  - 402
  - 452
  - 502
  - 552
  - 602
  - 652
  - 702
  - 752
  - 802
  - 852
  - 902
  - 952
output_dir: ../output
output_file_stem: output_file
visualization:
  force_continuous_object_qoi: true
  object_jitter: 0.5
  output_visualization_dir: ../output
  output_visualization_file_stem: output_file
  rank_qoi: work
  x_ranks: 8
  y_ranks: 4
  z_ranks: 1
work_model:
  name: AffineCombination
  parameters:
    alpha: 1.0
    beta: 1.0e-08
    gamma: 0.0
