# Specify input
from_data:
  data_stem: ../data/synthetic_lb_data/data
  phase_ids:
  - 0
check_schema: false

# Specify work model
work_model:
  name: AffineCombination
  parameters:
    beta: 1.0
    gamma: 0.0

# Specify algorithm
algorithm:
  name: PrescribedPermutation
  phase_id: 0
  parameters:
    permutation: {0: 3, 1: 3, 2: 0, 3: 0, 4: 3, 5: 2, 6: 0, 7: 0, 8: 1}

# Specify output
output_dir: ../output
output_file_stem: output_file
write_JSON:
  compressed: false
  suffix: json
  communications: true
  offline_lb_compatible: false
visualization:
  x_ranks: 2
  y_ranks: 2
  z_ranks: 1
  object_jitter: 0.5
  rank_qoi: load
  object_qoi: load
  save_meshes: true
  force_continuous_object_qoi: true
  output_visualization_dir: ../output
  output_visualization_file_stem: output_file
