# Specify input
from_data:
  data_stem: ../data/nolb-8color-16nodes-11firstphases/data
  phase_ids:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
check_schema: false

# Specify work model
work_model:
  name: AffineCombination
  parameters:
    alpha: 1.0
    beta: 1.0e-08
    gamma: 0.0

# Specify algorithm
algorithm:
  name: PhaseStepper

# Specify output
terminal_background: light
output_dir: ../output
output_file_stem: output_file
n_ranks: 32
LBAF_Viz:
  x_ranks: 8
  y_ranks: 4
  z_ranks: 1
  object_jitter: 0.5
  rank_qoi: work
  object_qoi: load
  save_meshes: true
  force_continuous_object_qoi: true
