# Specify input
from_data:
  data_stem: ../data/synthetic-blocks/synthetic-dataset-blocks
  phase_ids:
  - 0
check_schema: false

# Specify work model
work_model:
  name: AffineCombination
  parameters:
    alpha: 1.0
    beta: 1.0
    gamma: 1.0

# Specify algorithm
algorithm:
  name: PhaseStepper

# Specify output
output_dir: ../output
output_file_stem: synthetic-dataset-blocks
visualization:
  x_ranks: 2
  y_ranks: 2
  z_ranks: 1
  object_jitter: 0.5
  rank_qoi: load
  object_qoi: load
  save_meshes: true
  force_continuous_object_qoi: true
  output_visualization_dir: ../output
  output_visualization_file_stem: output_file

write_JSON:
  compressed: False
  suffix: json
  communications: True
  offline_LB_compatible: True
