# Specify input
from_data:
  data_stem: /home/pierrelp/Develop/NGA/vt-tv/source/tests/unit/lb_test_data/data
  phase_ids:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
check_schema: False

# Specify work model
work_model:
  name: AffineCombination
  parameters:
    alpha: 1.0
    beta: 1.0e-08
    gamma: 0.0

# Specify algorithm
algorithm:
  name: PhaseStepper

# Specify output
output_dir: ../output
output_file_stem: output_file
visualization:
  x_ranks: 2
  y_ranks: 2
  z_ranks: 1
  object_jitter: 0.5
  rank_qoi: load
  object_qoi: load
  save_meshes: true
  force_continuous_object_qoi: true
  output_visualization_dir: ../output
  output_visualization_file_stem: output_file

write_JSON:
  compressed: False
  suffix: json
  communications: True
  offline_LB_compatible: True
