# Specify input
from_data:
  data_stem: ../data/user-defined-memory-toy-problem/toy_mem
  phase_ids:
    - 0

# Specify work model
work_model:
  name: AffineCombination
  parameters:
    alpha: 1.0
    beta: 0.0
    gamma: 0.0
    upper_bounds:
      max_memory_usage: 8000000000.0

# Specify algorithm
algorithm:
  name: InformAndTransfer
  parameters:
    n_iterations: 4
    n_rounds: 4
    fanout: 4
    order_strategy: arbitrary
    transfer_strategy: Clustering
    criterion: Tempered
    max_objects_per_transfer: 32
    deterministic_transfer: true

# Specify output
overwrite_validator: false
check_schema: true
terminal_background: light
output_dir: ../output
output_file_stem: output_file
n_ranks: 4
LBAF_Viz:
  x_ranks: 2
  y_ranks: 2
  z_ranks: 1
  object_jitter: 0.5
  rank_qoi: load
  #rank_qoi: homed_blocks_ratio
  object_qoi: load
  #object_qoi: shared_block_id
  save_meshes: true
