# Specify input
from_data:
  data_stem: ../data/user-defined-memory-toy-problem/toy_mem
  phase_ids:
  - 0
check_schema: false
overwrite_validator: false

# Specify work model
work_model:
  name: AffineCombination
  parameters:
    alpha: 1.0
    beta: 0.0
    gamma: 0.0
    upper_bounds:
      max_memory_usage: 8000000000.0

# Specify algorithm
algorithm:
  name: InformAndTransfer
  phase_id: 0
  parameters:
    n_iterations: 4
    n_rounds: 2
    fanout: 2
    order_strategy: arbitrary
    transfer_strategy: Clustering
    criterion: Tempered
    max_objects_per_transfer: 32
    deterministic_transfer: true

# Specify output
output_dir: ../output
output_file_stem: output_file
write_JSON:
  compressed: true
  suffix: json
  communications: true
  offline_LB_compatible: true
visualization:
  x_ranks: 2
  y_ranks: 2
  z_ranks: 1
  object_jitter: 0.5
  rank_qoi: load
  object_qoi: load
  save_meshes: true
  force_continuous_object_qoi: true
  output_visualization_dir: ../output
  output_visualization_file_stem: output_file
