# Specify input
from_data:
  data_stem: ../../data/synthetic_lb_data/data
  phase_ids:
    - 0

# Specify work model
work_model:
  name: AffineCombination
  parameters:
    alpha: 1.0
    beta: 0.0
    gamma: 0.0

# Specify algorithm
brute_force_optimization: true
algorithm:
  name: InformAndTransfer
  parameters:
    n_iterations: 8
    n_rounds: 4
    fanout: 4
    order_strategy: element_id
    transfer_strategy: Recursive
    criterion: Tempered
    max_objects_per_transfer: 8
    deterministic_transfer: true

# Specify output
logging_level: info
terminal_background: light
output_dir: ../../output
output_file_stem: output_file
n_ranks: 4
