name: Code Analysis
on: push
jobs:
  pylint:
    runs-on: ubuntu-latest
    env:
      home_dir: /home/runner/work/LB-analysis-framework/LB-analysis-framework

    steps:
      - uses: actions/checkout@v2

      - name: Install packages
        run: |
          sudo apt-get update && sudo apt-get upgrade -y

      - name: Python Setup
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          cd ${{ env.home_dir }}
          python -m pip install --upgrade pip
          pip install -r requirements-3.8.txt

      - name: Run pylint
        run: |
          cd ${{ env.home_dir }}
          pylint --rcfile=.pylintrc src
        continue-on-error: true

