name: Code Analysis
on: push
jobs:
  pylint:
    runs-on: ubuntu-latest
    env:
      home_dir: /home/runner/work/LB-analysis-framework/LB-analysis-framework

    steps:
      - uses: actions/checkout@v3

      - name: Install packages
        run: |
          sudo apt-get update && sudo apt-get upgrade -y

      - name: Python Setup
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          cd ${{ env.home_dir }}
          python -m pip install --upgrade pip
          pip install -r requirements-3.8.txt

      - name: Register pylint problem matcher
        run: |
          echo "::add-matcher::.github/workflows/matchers/pylint-warning.json"
          echo "::add-matcher::.github/workflows/matchers/pylint-error.json"

      - name: Run pylint
        run: |
          cd ${{ env.home_dir }}
          pylint --rcfile=.pylintrc src --output-format=text,json:output/pylint-report.json
        continue-on-error: true

      - name: Archive pylint report
        uses: actions/upload-artifact@v3
        with:
          name: pylint-report
          path: output/pylint-report.json
          retention-days: 1

