name: Deploy docs

on: push

jobs:
  build-and-deploy-docs:
    runs-on: ubuntu-latest
    env:
      project-directory: /home/runner/work/LB-analysis-framework/LB-analysis-framework
      docs-directory: /home/runner/work/LB-analysis-framework/LB-analysis-framework/docs
      docs-output: /home/runner/work/LB-analysis-framework/LB-analysis-framework/docs/output
      docs-generator: /home/runner/work/LB-analysis-framework/LB-analysis-framework/m.css/documentation
      python-version: '3.8'

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ env.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.python-version }}
          architecture: 'x64'
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip3 install docutils jinja2 pygments
      - name: Clone documentation generator
        working-directory: ${{ env.project-directory }}
        run: |
          git clone https://github.com/mosra/m.css.git
      - name: Download JSON_data_files_validator
        run: |
           lbaf-vt-data-files-validator-loader
      - name: Build documentation
        working-directory: ${{ env.docs-generator }}
        run: |
          ls
          less python.py
          python python.py ${{ env.docs-directory }}/docs_config.py
      # .nojekyll file is needed for GitHub Pages to know it's getting a ready webpage
      # and there is no need to generate anything
      - name: Generate nojekyll file
        working-directory: ${{ env.docs-output }}
        run: touch .nojekyll
      # This action moves the content of `generated_docs` to the `deploy-doc-site` branch
      # It only runs on pushes to main and develop
      - name: Deploy docs
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GH_PAT }}
          branch: master
          repository-name: DARMA-tasking/DARMA-tasking.github.io
          target-folder: lbaf_docs
          folder: ${{ env.docs-output }}
          clean: true
