name: PR checks (trailing whitespace)

on: pull_request

jobs:
  check:
    name: Find Trailing Whitespace
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DARMA-tasking/find-trailing-whitespace@master
        with:
          exclude: "doc;.png$;nolb-8color-16nodes-data;nolb-8color-16nodes-every50phases" # ; separated path to exclude
